name: roomies_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cloud_firestore: ^5.4.5
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.2
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.2
  intl: ^0.19.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  mockito: ^5.4.4

flutter:

  uses-material-design: true
  # assets:
  #   - assets/
  #   - assets/images
  #   - assets/lotties
